# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievesolapp', '0002_auto_20190920_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eventcategory',
                'verbose_name_plural': 'eventcategories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'mediacategory',
                'verbose_name_plural': 'mediacategories',
                'ordering': ('name',),
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogCategory',
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ('name',), 'verbose_name': 'blogcategory', 'verbose_name_plural': 'blogcategories'},
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='achievesolapp.EventCategory'),
        ),
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='achievesolapp.MediaCategory'),
        ),
    ]
