# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-23 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievesolapp', '0005_auto_20190923_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
