# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-24 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievesolapp', '0007_auto_20190924_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='blog_name',
        ),
    ]
