# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-24 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievesolapp', '0010_auto_20190924_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='blogcategory',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='eventcategory',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='category',
            new_name='mediacategory',
        ),
    ]
