# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-24 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievesolapp', '0012_media_available'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='media',
            index_together=set([('id', 'slug')]),
        ),
    ]
